# -*- coding: utf-8 -*-
"""PARTS pour client.md — textes courts, apostrophes françaises."""

PARTS_CLIENT = [
    (
        ("1–20", 20, "Includes + globals", "Outils cliente Paroles."),
        "Tu lances **`paroles_client …`** : cette zone garde ce qui dure **toute la commande** — **`-v`**, contexte **TLS** (`g_tls_cli`, `g_io_ssl`), **clés Ed25519** si **`--key`** / **`--server-pub`** (option **signature** du cours). Moment : **dès que le binaire démarre**, **avant** le `switch` des sous-commandes dans `main`.",
        "À chaque sous-commande invoquée depuis le shell.",
        "Variables et contexte partagés (`verbose`, TLS, PEM).",
        "Déclarations `static` ; includes **proto, auth, tls, net, wire**.",
    ),
    (
        ("22–54", 33, "Helpers", "Pseudo, SNI, nonce fichier."),
        "**Trois utilitaires** : **`pad_nom`** remplit **`PAROLES_NOM_LEN`**, **`tls_sni_for_host`** remplace **`::1`** par **`localhost`** (SNI pratique avec cert locaux), puis **`nonce_*`** lit/écrit **`/tmp/paroles_nonce_<port>_<uid>`** pour les **numéros AUTH** optionnels. Pense-y quand le cours parle **preuve + anti-rejeu**.",
        "**`cmd_reg`** (pseudo fixe) puis **`one_cmd_authed`** (nonce).",
        "Pseudo prêt ; SNI cohérent ; compteur rejouable sur disque.",
        "`snprintf`, `fopen`, lecture/écriture entier, fermeture fichier.",
        [
            ("pad_nom", "Pseudo fixe", "**memset** + **strncpy**."),
            ("tls_sni_for_host", "Nom TLS", "::1 → localhost."),
            ("nonce_path + I/O", "Fichier nonce", "chemin puis `fscanf`/`fprintf`."),
        ],
    ),
    (
        ("56–104", 49, "one_cmd_plain", "Une requête TCP sans AUTH."),
        "Scène **`reg`** ou commande **sans `--key`** : **connect** IPv6, **handshake TLS** si `--tls`, **`conn_writen`** du buffer, **`conn_read_upto`** pour la réponse (taille libre), fermeture **`SSL_shutdown`/`close`**. `g_io_ssl` rappelle quel canal **`conn_*`** utilise.",
        "**`cmd_reg`** et toutes commandes **sans** PEM privée (hors chemin signé).",
        "Retourne la taille de la réponse lue ou **-1**.",
        "**`tcp6_connect`**, branche **OpenSSL**, **`conn_writen` / `conn_read_upto`**.",
        [
            ("tcp6_connect", "Canal TCP", "socket + **connect**."),
            ("SSL_connect + SNI", "TLS cliente", "facultatif."),
            ("conn_writen / conn_read_upto", "Échange application", "timeout **PAROLES_TCP_TIMEOUT_MS**."),
        ],
    ),
    (
        ("106–197", 92, "one_cmd_authed", "TLS + AUTH puis métier."),
        "Avec **`--key`**, chaque commande (sauf inscription) **ouvre une session** : fabrique le paquet **AUTH** (nonce lu sur disque, signature **Ed25519**), lit **AUTH_OK** taille fixe, **vérifie** la signature serveur si **`--server-pub`**, **incrémente** le nonce, **puis envoie** le vrai message métier (**`conn_writen`** + **`conn_read_upto`**). Label **`fail:`** nettoie SSL/socket.",
        "Commandes après **`REG`** quand PEM chargée (`one_cmd`).",
        "Même type de retour que **`one_cmd_plain`** ou erreur.",
        "Enchaînement **wire + EVP + `goto fail`**.",
        [
            ("read_nonce + sign", "Preuve client", "**wire** + **`paroles_ed25519_sign`**."),
            ("conn_readn AUTH_OK", "Réponse fixe", "**wire_get** successivement."),
            ("verify serveur", "Confiance réciproque", "**`paroles_ed25519_verify`** si clé pub prof."),
            ("write_nonce(+1)", "Anti-rejeu", "mise à jour fichier **`/tmp`**."),
            ("commande suivante", "Métier", "**`conn_writen`** puis **`conn_read_upto`**."),
        ],
    ),
    (
        ("199–203", 5, "one_cmd", "Dispatcheur."),
        "**Si PEM privée ⇒ `one_cmd_authed`, sinon `one_cmd_plain`.** Point unique d’entrée réseau pour les **`cmd_*`**. ",
        "**Toutes les commandes** sauf **`cmd_reg`** qui force le chemin plain.",
        "Choix automatique AUTH ou non.",
        "Test **`g_auth_priv`** puis appel fonction adaptée.",
    ),
    (
        ("205–225", 21, "fill_ed25519_cle_from_pem", "PEM public → champ 113."),
        "Quand **`reg`** prend un fichier **PEM public**, ce helper lit la **clé brute 32 octets** et **remplit les 113 positions** cours (**copie puis zéros**).",
        "Branche **`pub_pem`** de **`cmd_reg`**.",
        "Buffer **`cle`** prêt pour **`REG`**.",
        "**PEM_read_PUBKEY** + contrôle Ed25519 + **`EVP_PKEY_get_raw_public_key`**.",
        [
            ("PEM_read_PUBKEY", "Charge PEM public", "vérif type Ed25519."),
            ("memcpy + zeros", "Champ inscription", "**32 premiers octets** + bourrage."),
        ],
    ),
    (
        ("227–253", 27, "cmd_reg", "CODEREQ 1."),
        "**`./paroles_client host port reg Pseudo [pub.pem]`** : construit **`REG`** (CODEREQ + nom + cle), passe par **`one_cmd_plain`**, contrôle **`REG_OK`**, affiche **`OK id=… udp=…`**.",
        "Première étape utilisateur cours.",
        "Identifiant + port UDP attribués par le serveur.",
        "**`wire_put_*`**, **`one_cmd_plain`**, parse réponse (**`wire_get`**).",
    ),
    (
        ("255–278", 24, "cmd_newgroup", "CODEREQ 3."),
        "**`newgroup uid nom`** après inscription : message **NEW_GROUP** via **`one_cmd`** (AUTH possible), vérif **NEW_GROUP_OK**, affiche **id multicast** avec **`inet_ntop`**.",
        "Création de salon depuis le terminal cliente.",
        "Numéro de groupe + adresse multicast + port.",
        "Longueur nom **u16** + copie puis décodage réponse.",
    ),
    (
        ("280–295", 16, "cmd_invite", "CODEREQ 5."),
        "**`invite admin idg uid …`** construit une table d’uids + **pads** cours puis attend un **ACK** simple.",
        "Admin TP qui invite plusieurs comptes.",
        "Succès si premier octet réponse = **ACK**.",
        "Boucle **`wire_put_u32` + `wire_put_zeros`** pour chaque invité.",
    ),
    (
        ("297–327", 31, "cmd_listinv", "CODEREQ 6."),
        "**`listinv uid`** : affiche combien d’invitations puis chaque **idg / nom / admin** selon le format serveur.",
        "Savoir quels salons attendent une réponse.",
        "Sortie **printf** structurée.",
        "Parse **`LIST_INV_OK`** : compteur puis boucle champs.",
        [
            ("Requête", "LIST_INV + uid", "**`one_cmd`**."),
            ("Parse", "Chaînes variables", "**`wire_get_u32/u16`** + **memcpy**."),
        ],
    ),
    (
        ("329–347", 19, "cmd_ans", "CODEREQ 8."),
        "**`ans uid idg code`** (accepter / refuser / quit selon le cours) ; affiche **ACK** ou **JOIN** suivant premier octet retour.",
        "Réponse cliente à une invitation.",
        "Message humain **`OK ack`** ou **`OK join`**.",
        "Petit buffer fixe envoyé puis **switch** sur code retour.",
    ),
    (
        ("349–375", 27, "cmd_listmem", "CODEREQ 10."),
        "**`listmem uid idg`** (ou idg global selon valeur) ; décode liste de **(uid,pseudo)**.",
        "Inspecter membres après avoir rejoint.",
        "**printf** lignes tableau.",
        "Parse après **`LIST_MEM_OK`** (+ compteurs cours).",
        [
            ("Requête", "LIST_MEM", "**wire** fixe."),
            ("Lecture tableau", "Boucles", "**noms longueurs fixes**."),
        ],
    ),
    (
        ("377–397", 21, "cmd_post", "CODEREQ 12."),
        "**`post uid idg texte`** envoie longueur + texte puis attend **POST_OK** pour afficher le **numéro de billet**.",
        "Publication dans un groupe.",
        "Confirmation **OK billet numb=…**.",
        "Tampon **`msg`** + **`memcpy`** texte cours.",
    ),
    (
        ("399–416", 18, "cmd_reply", "CODEREQ 14."),
        "**`reply`** référencée par **numb** puis texte comme **POST**.",
        "Ajouter une réponse à un billet existant.",
        "**OK reply** après **REPLY_OK**.",
        "**`wire_put`** entiers puis chaîne UTF-8 taille cours.",
    ),
    (
        ("418–453", 36, "cmd_feed", "CODEREQ 16."),
        "**`feed uid idg numb numr`** récupère le morceau de fil après l’ancre (**numb/numr**) et affiche chaque ligne retournée.",
        "Rattraper l’historique sans tout retélécharger à la main.",
        "Sortie **printf** par événement.",
        "Parse **FEED_OK** avec boucle auteurs + textes.",
    ),
    (
        ("455–504", 50, "Notifs UDP", "listen_udp / listen_mcast."),
        "Deuxième terminal TP : **`listen_udp portUDP`** (notifs personnelles serveur ↔ client) ou **`listen_mcast adresse port`** (radio du salon). **`write_notif_line`** imprime **`code`** + **`idg`** depuis **6 octets big-endian**, comme envoyé par **`server.c`**.",
        "Tests UDP / multicast du polycopié.",
        "Une ligne **`code idg`** par datagramme reçu.",
        "**`udp6_bind_any` / `udp6_mcast_recv_socket`** + **`udp6_recv`** en boucle temporelle.",
        [
            ("write_notif_line", "Décodage 6 octets", "**u16 BE + u32 BE**."),
            ("cmd_listen_udp", "Unicast", "**bind_any** + timeouts."),
            ("cmd_listen_mcast", "Multicast", "**JOIN + recv** jusqu’au temps imparti."),
        ],
    ),
    (
        ("506–529", 24, "usage | client_tls_atexit", "Aide et nettoyage."),
        "**Sans bons arguments** : **`usage`** rappelle toutes sous-commandes (y compris **listen_udp/listen_mcast**). **`client_tls_atexit`** fermet **SSL_CTX** et **EVP_PKEY** via **`atexit`** pour sorties propres.",
        "Erreur parsing ou fin de processus.",
        "Pas de fuite grossière OpenSSL.",
        "**fprintf** stderr + **`paroles_tls_ctx_free` / `EVP_PKEY_free`**.",
        [
            ("usage", "Synopsis", "**fprintf** multi-lignes."),
            ("client_tls_atexit", "Libère ressources", "enregistré une seule fois."),
        ],
    ),
    (
        ("531–649", 119, "main", "Analyse argv et dispatch."),
        "Tu tapes **`paroles_client [-v] [--tls ca] [--key priv] [--server-pub pub] host port cmd args…`** : **`main`** lit les options, construit le contexte TLS/Ed25519, puis compare **`cmd`** avec **`reg`**, **`newgroup`**, etc. **Erreurs** ⇒ **usage** + code 1.",
        "Point d’entrée binaire réel.",
        "Code retour **0** succès, **1** échec.",
        "Chaîne de **`strcmp`** + conversions **`atoi`** ; **`malloc`** pour liste d’uids d’**invite**.",
        [
            ("Parse options", "TLS / clés", "avance l’index **`i`** dans **`argv`**."),
            ("Dispatch `cmd`", "Sous-commandes", "appels **`cmd_*`**."),
            ("invite", "Liste variable", "**malloc** + boucle **`atoi`**."),
        ],
    ),
]
