#ifndef PAROLES_PROTO_H
#define PAROLES_PROTO_H

#include <stdint.h>

/* Codes requête / réponse (big-endian sur le fil) */
#define PAROLES_AUTH_CLIENT 0 /* étape 3 — non utilisé en étape 1 */
#define PAROLES_REQ_REGISTER 1
#define PAROLES_RESP_REGISTER 2
#define PAROLES_REQ_CREATE_GROUP 3
#define PAROLES_RESP_CREATE_GROUP 4
#define PAROLES_REQ_INVITE 5
#define PAROLES_REQ_LIST_INVITES 6
#define PAROLES_RESP_LIST_INVITES 7
#define PAROLES_REQ_INVITE_ANSWER 8
#define PAROLES_RESP_JOINED 9
#define PAROLES_REQ_LIST_MEMBERS 10
#define PAROLES_RESP_LIST_MEMBERS 11
#define PAROLES_REQ_POST 12
#define PAROLES_RESP_POST 13
#define PAROLES_REQ_REPLY 14
#define PAROLES_RESP_REPLY 15
#define PAROLES_REQ_LIST_FEED 16
#define PAROLES_RESP_LIST_FEED 17

#define PAROLES_NOTIF_MCAST_NEW 18
#define PAROLES_NOTIF_MCAST_JOIN 19
#define PAROLES_NOTIF_MCAST_LEAVE 20
#define PAROLES_NOTIF_MCAST_CLOSE 21
#define PAROLES_NOTIF_UDP_INVITE 22
#define PAROLES_NOTIF_UDP_READ 23

#define PAROLES_ACK 24
#define PAROLES_ERR 31

#define PAROLES_NOM_LEN 10
#define PAROLES_CLE_LEN 113

#define PAROLES_INV_ACCEPT 1
#define PAROLES_INV_REFUSE 0
#define PAROLES_INV_LEAVE 2

#endif
