#ifndef PAROLES_PROTO_H
#define PAROLES_PROTO_H

#include <stdint.h>

#define PAROLES_NOM_LEN 10
#define PAROLES_CLE_LEN 113
#define PAROLES_IP6_BIN 16

/* Étape 3 — authentification (signature des 3 champs : CODEREQ, ID, NUM). */
#define PAROLES_CODEREQ_AUTH 0
#define PAROLES_CODEREQ_AUTH_OK 25
#define PAROLES_ED25519_SIG_LEN 64

#define PAROLES_CODEREQ_REG 1
#define PAROLES_CODEREQ_REG_OK 2
#define PAROLES_CODEREQ_NEW_GROUP 3
#define PAROLES_CODEREQ_NEW_GROUP_OK 4
#define PAROLES_CODEREQ_INVITE 5
#define PAROLES_CODEREQ_LIST_INV 6
#define PAROLES_CODEREQ_LIST_INV_OK 7
#define PAROLES_CODEREQ_INV_ANS 8
#define PAROLES_CODEREQ_JOIN_OK 9
#define PAROLES_CODEREQ_LIST_MEM 10
#define PAROLES_CODEREQ_LIST_MEM_OK 11
#define PAROLES_CODEREQ_POST 12
#define PAROLES_CODEREQ_POST_OK 13
#define PAROLES_CODEREQ_REPLY 14
#define PAROLES_CODEREQ_REPLY_OK 15
#define PAROLES_CODEREQ_FEED 16
#define PAROLES_CODEREQ_FEED_OK 17
#define PAROLES_CODEREQ_ACK 24
#define PAROLES_CODEREQ_ERR 31

#define PAROLES_NOTIF_NEW_MSG 18
#define PAROLES_NOTIF_JOIN 19
#define PAROLES_NOTIF_LEAVE 20
#define PAROLES_NOTIF_CLOSE 21
#define PAROLES_NOTIF_INV_UDP 22
#define PAROLES_NOTIF_FETCH 23

#define PAROLES_INV_PAD 4
#define PAROLES_ERR_TAIL 15
#define PAROLES_MAX_BODY (64 * 1024)

#endif
